name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm audit
        continue-on-error: true
      - run: npm audit fix
      - run: npm update
      - run: git commit -m "fixed and updated dependencies" || echo "No changes to commit"
      - run: git push || echo "No changes to push"